### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by podehnal** [jpmckinney/image-proxy#16]
Hi!

Thanks for the package. I keep receiving the following error when I try to use it per the instructions. 

Any idea what this might be?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

**Comment by jpmckinney** [comment]
Hmm, try http://stackoverflow.com/questions/22960703/node-js-events-js-72-throw-er-unhandled-error-event

**Comment by jpmckinney** [comment]
What image are you trying to proxy when the error occurs?

**Comment by podehnal** [comment]
I tried killing all node process and there is nothing else using  port:5000. 

The image I am using is the one in the repo readme. 
```
npm install
npm start
curl -I http://localhost:5000/http%3A%2F%2F1.gravatar.com%2Favatar%2F60f641dfbb4215f1f6d6c059eebf1848/240/80.jpg
```

Here is the full error message after I issue the curl command in a separate terminal window

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/petr/.nvm/v0.10.24/bin/npm" "start"
npm ERR! node v0.10.24
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! image-proxy@0.0.7 start: `./bin/image-proxy`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the image-proxy@0.0.7 start script './bin/image-proxy'.
npm ERR! This is most likely a problem with the image-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/image-proxy
npm ERR! You can get their info via:
npm ERR!     npm owner ls image-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/petr/Desktop/Petr/_PROJECTS/image-proxy/npm-debug.log
```
Thanks !

**Comment by podehnal** [comment]
Ok figured it out... 

I needed to run the following before I could use the 'gm' node module.  
``` 
brew install imagemagick
brew install graphicsmagick
```

Thanks again!

**Comment by jpmckinney** [comment]
Thanks for posting the solution!

**Comment by jpmckinney** [comment]
I've added a line to the readme about this: https://github.com/jpmckinney/image-proxy#getting-started
