### ISSUE TITLE
If image responds after timeout then the node process crashes

### ISSUE THREAD

**Issue by struan** [jpmckinney/image-proxy#9]
The server falls over with a stack trace:

```
http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/app-path/node_modules/express/node_modules/connect/lib/patch.js:133:22)
    at ServerResponse.setWriteHeadHeaders (/app-path/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:80:19)
    at ServerResponse.writeHead (/app-path/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:39:36)
    at gm.<anonymous> (/app-path/node_modules/image-proxy/lib/image-proxy.js:69:19)
    at cb (/app-path/node_modules/image-proxy/node_modules/gm/lib/command.js:265:16)
    at gm._spawn (/app-path/node_modules/image-proxy/node_modules/gm/lib/command.js:253:7)
    at /app-path/node_modules/image-proxy/node_modules/gm/lib/command.js:117:19
    at series (/app-path/node_modules/image-proxy/node_modules/gm/node_modules/array-series/index.js:11:36)
    at gm._preprocess (/app-path/node_modules/image-proxy/node_modules/gm/lib/command.js:154:5)
```

And pointing the proxy at the image served by this example node app should replicate the error:

https://gist.github.com/chrismytton/5f0ac2fd54e0d3872f0a

**Comment by jpmckinney** [comment]
Thanks for reporting! Fixed.

**Comment by struan** [comment]
Thanks for the quick fix :)
